IMDB:
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: at-main | domain: .imdb.com
    # You need to replace this value with your own, the default value is for illustrative purposes only
    COOKIEATMAIN: Atza|IwEBINiZ-kO5yHwk7TgP6tHf60ywvDe481NnZvoAFmhF-brAYZiTWJzUiasxDs7jJPZ9BilX3O7feDAWLDIeb03_IAhKMtEqFNzu8_J0MWzrDaYNqYA--qne5R7GzupvHLHo_WT8LljjxnC62Di8AWL5URV9sepeul1aDLpO1TwJcGmwnAxKkJSOyys9MqFX2QENXfhMnBDIXslnHSCi8VSvptIJneTGmN7b9jduvpmOb2FDxw
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: ubid-main | domain: .imdb.com
    # You need to replace this value with your own, the default value is for illustrative purposes only
    COOKIEUBIDMAIN: 132-2740251-5510023
    # Array of IMDb lists that you would like synced to Trakt
    # If this array is empty, all IMDb lists will be synced to Trakt
    # Keep in mind the maximum number of lists you can have in Trakt: https://twitter.com/trakt/status/1536751362943332352
    # In order to get the ID of an IMDb list, open it from a browser - the ID is in the URL with format ls#########
    LISTS:
        - ls009122857
        - ls070081123
        - ls009124039
        - ls009124517
SYNC:
    # Sync mode to be used when running the application
    # The value must be one of the following:
    #   full     - sync all IMDb items by adding, deleting and updating Trakt resources
    #   add-only - sync only newly added IMDb items to Trakt
    #   dry-run  - identify what IMDb items would be added, deleted or updated on Trakt
    MODE: full
    # Whether to skip history sync or not. If set to true, history sync will be skipped
    # IMDb doesn't offer functionality similar to Trakt history, hence why there can't be a direct mapping between them
    # The syncer will assume you have watched an item if you've submitted a rating for it
    # If the above is satisfied and your history for this item is empty, then a new history entry will be added...
    SKIPHISTORY: true
TRAKT:
    # Trakt app client ID
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTID: 02d66aec4f62502968ad93fd518979750f4c6c2306b75b8232cdb72fb2980ec0
    # Trakt app client secret
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTSECRET: 2170d94b62c91ddfc73a354f8f93de2b38040b50a222b5ebd76318117ebed527
    # Trakt account email address (not to be confused with username)
    # You need to replace this value with your own, the default value is for illustrative purposes only
    EMAIL: stumaxis@gmail.com
    # Trakt account password
    # You need to replace this value with your own, the default value is for illustrative purposes only
    PASSWORD: jkPfVud@vgibE6vNQkYc
